repos:
    -   repo: https://github.com/psf/black
        rev: 22.3.0
        hooks:
        -   id: black
    -   repo: https://github.com/PyCQA/isort
        rev: 5.10.1
        hooks:
        -   id: isort
            name: Sort Python imports
            args: [--profile, black, --filter-files]
    -   repo: local
        hooks:
        -   id: pytest-check
            name: pytest-check
            entry: pytest ./tests
            language: system
            pass_filenames: false
            always_run: true
